In [1]:
from datetime import date
import pandas as pd
import os
import glob

# Load data

In [2]:
parent_directory = "/home/schmiedc/FMP_Docs/Projects/Bioactives_data/"

# Path 
data_path =  parent_directory  + "aggregated_data/IMTM_HepG2/"
save_path = parent_directory  + "results/"
annot_path = parent_directory  + "annotations/"

In [3]:
### loading latest data
Data = []
plates = ["B1001","B1002","B1003","B1004","B1005","B1006","B1007"]
batches = ["R1", "R2", "R3", "R4"]
path = data_path

for batch in batches:
    for plate in plates:
    
        file_type = '/*[0-9]_HepG2_10uM_*' + plate + "_" + batch + "_CP_Profiles_Aggregated.csv"
        
        files_temp = glob.glob(path + file_type)
        max_file = max(files_temp, key=os.path.getctime)
    
        ### load file
        Data_Temp = pd.read_csv(max_file)
        print(batch, plate, "has shape", Data_Temp.shape)  
        ### put to list
        Data.append(Data_Temp)

### concat all batches together
Data_aggregated = pd.concat(Data)
Data_aggregated = Data_aggregated.reset_index(drop = True)

print("Aggregated Data has shape ", Data_aggregated.shape)

R1 B1001 has shape (378, 2981)
R1 B1002 has shape (382, 2981)
R1 B1003 has shape (384, 2981)
R1 B1004 has shape (379, 2981)
R1 B1005 has shape (379, 2981)
R1 B1006 has shape (381, 2981)
R1 B1007 has shape (380, 2981)
R2 B1001 has shape (379, 2981)
R2 B1002 has shape (384, 2981)
R2 B1003 has shape (383, 2981)
R2 B1004 has shape (380, 2981)
R2 B1005 has shape (382, 2981)
R2 B1006 has shape (380, 2981)
R2 B1007 has shape (381, 2981)
R3 B1001 has shape (379, 2981)
R3 B1002 has shape (382, 2981)
R3 B1003 has shape (382, 2981)
R3 B1004 has shape (381, 2981)
R3 B1005 has shape (380, 2981)
R3 B1006 has shape (381, 2981)
R3 B1007 has shape (381, 2981)
R4 B1001 has shape (383, 2981)
R4 B1002 has shape (383, 2981)
R4 B1003 has shape (384, 2981)
R4 B1004 has shape (378, 2981)
R4 B1005 has shape (379, 2981)
R4 B1006 has shape (381, 2981)
R4 B1007 has shape (382, 2981)
Aggregated Data has shape  (10668, 2981)

In [4]:
Data_aggregated.head()

,Metadata_Batch,Metadata_Plate,Metadata_Well,Metadata_Object_Count,Nuc_AreaShape_Area,Nuc_AreaShape_BoundingBoxArea,Nuc_AreaShape_BoundingBoxMaximum_X,Nuc_AreaShape_BoundingBoxMaximum_Y,Nuc_AreaShape_BoundingBoxMinimum_X,Nuc_AreaShape_BoundingBoxMinimum_Y,...,Cyto_Texture_Variance_Mito_10_02_256,Cyto_Texture_Variance_Mito_10_03_256,Cyto_Texture_Variance_Mito_3_00_256,Cyto_Texture_Variance_Mito_3_01_256,Cyto_Texture_Variance_Mito_3_02_256,Cyto_Texture_Variance_Mito_3_03_256,Cyto_Texture_Variance_Mito_5_00_256,Cyto_Texture_Variance_Mito_5_01_256,Cyto_Texture_Variance_Mito_5_02_256,Cyto_Texture_Variance_Mito_5_03_256
0,HepG2_10uM,B1001_R1,A01,401,443.0,600.0,544.0,521.0,519.0,494.0,...,27.485077,27.159029,27.034550,27.474699,27.517895,27.098289,27.044748,27.476479,27.397701,26.846224
1,HepG2_10uM,B1001_R1,A02,960,358.0,484.0,533.0,532.0,507.5,509.0,...,18.149014,18.117806,17.896635,17.961329,18.167331,17.974684,17.838051,18.096688,18.167415,18.078164
2,HepG2_10uM,B1001_R1,A03,684,390.5,546.0,543.5,519.0,518.5,496.0,...,44.836899,42.719259,45.046219,44.485645,46.066105,44.490707,43.116350,43.774080,45.156351,43.194946
3,HepG2_10uM,B1001_R1,A04,1085,368.0,506.0,467.0,529.0,445.0,502.0,...,12.584591,12.365254,12.947254,12.847301,13.083285,12.951762,12.947011,12.526472,12.824263,13.057779
4,HepG2_10uM,B1001_R1,A05,91,378.0,567.0,339.0,443.0,319.0,423.0,...,79.650978,68.290535,73.153893,76.065323,73.855774,75.632614,75.405464,80.695778,79.210136,76.293587

In [5]:
# create correct metadata columns
metadataCol = Data_aggregated['Metadata_Plate'].str.split("_", n=1, expand=True)
metadataCol[1] = metadataCol[1].astype(str)
metadataCol = metadataCol.rename(columns={0: "Metadata_Plate", 1: "Metadata_Batch"})
metadataCol

      Metadata_Plate Metadata_Batch
0              B1001             R1
1              B1001             R1
2              B1001             R1
3              B1001             R1
4              B1001             R1
...              ...            ...
10663          B1007             R4
10664          B1007             R4
10665          B1007             R4
10666          B1007             R4
10667          B1007             R4

[10668 rows x 2 columns]

In [6]:
# drop faulty metadata columns
Data_aggregated_dropped = Data_aggregated.drop(['Metadata_Batch', 'Metadata_Plate'], axis=1)

In [7]:
Data_aggregated = pd.concat([metadataCol, Data_aggregated_dropped], axis=1)
print("Aggregated Data has shape ", Data_aggregated.shape)
Data_aggregated.head()

Aggregated Data has shape  (10668, 2981)

,Metadata_Plate,Metadata_Batch,Metadata_Well,Metadata_Object_Count,Nuc_AreaShape_Area,Nuc_AreaShape_BoundingBoxArea,Nuc_AreaShape_BoundingBoxMaximum_X,Nuc_AreaShape_BoundingBoxMaximum_Y,Nuc_AreaShape_BoundingBoxMinimum_X,Nuc_AreaShape_BoundingBoxMinimum_Y,...,Cyto_Texture_Variance_Mito_10_02_256,Cyto_Texture_Variance_Mito_10_03_256,Cyto_Texture_Variance_Mito_3_00_256,Cyto_Texture_Variance_Mito_3_01_256,Cyto_Texture_Variance_Mito_3_02_256,Cyto_Texture_Variance_Mito_3_03_256,Cyto_Texture_Variance_Mito_5_00_256,Cyto_Texture_Variance_Mito_5_01_256,Cyto_Texture_Variance_Mito_5_02_256,Cyto_Texture_Variance_Mito_5_03_256
0,B1001,R1,A01,401,443.0,600.0,544.0,521.0,519.0,494.0,...,27.485077,27.159029,27.034550,27.474699,27.517895,27.098289,27.044748,27.476479,27.397701,26.846224
1,B1001,R1,A02,960,358.0,484.0,533.0,532.0,507.5,509.0,...,18.149014,18.117806,17.896635,17.961329,18.167331,17.974684,17.838051,18.096688,18.167415,18.078164
2,B1001,R1,A03,684,390.5,546.0,543.5,519.0,518.5,496.0,...,44.836899,42.719259,45.046219,44.485645,46.066105,44.490707,43.116350,43.774080,45.156351,43.194946
3,B1001,R1,A04,1085,368.0,506.0,467.0,529.0,445.0,502.0,...,12.584591,12.365254,12.947254,12.847301,13.083285,12.951762,12.947011,12.526472,12.824263,13.057779
4,B1001,R1,A05,91,378.0,567.0,339.0,443.0,319.0,423.0,...,79.650978,68.290535,73.153893,76.065323,73.855774,75.632614,75.405464,80.695778,79.210136,76.293587

# Load EOS number

In [8]:
file_type = '/*[0-9]_' + 'Annotation2_IMTM_HepG2.csv'
files = glob.glob(annot_path + file_type)

### gets latest file
max_file = max(files, key=os.path.getctime)

### load file
Annotation_Bioactives = pd.read_csv(max_file)
Annotation_Bioactives.shape

(10752, 6)

In [9]:
Annotation_Bioactives.head()

,Metadata_Plate,Metadata_Well,Metadata_EOS,Metadata_Concentration,Metadata_Partner,Metadata_Batch
0,B1001,A01,EOS100001,10,IMTM,R4
1,B1001,A02,EOS100089,10,IMTM,R4
2,B1001,A03,EOS100009,10,IMTM,R4
3,B1001,A04,EOS100097,10,IMTM,R4
4,B1001,A05,EOS100017,10,IMTM,R4

# Merge with EOS number

In [10]:
Data_Bioactives = pd.merge(
    Annotation_Bioactives, 
    Data_aggregated, 
    on = ["Metadata_Batch", "Metadata_Plate", "Metadata_Well"], 
    how = "inner")
        
print("Aggregated and annotated Data has shape ", Data_Bioactives.shape)

Aggregated and annotated Data has shape  (10668, 2984)

In [11]:
Data_Bioactives.head()

,Metadata_Plate,Metadata_Well,Metadata_EOS,Metadata_Concentration,Metadata_Partner,Metadata_Batch,Metadata_Object_Count,Nuc_AreaShape_Area,Nuc_AreaShape_BoundingBoxArea,Nuc_AreaShape_BoundingBoxMaximum_X,...,Cyto_Texture_Variance_Mito_10_02_256,Cyto_Texture_Variance_Mito_10_03_256,Cyto_Texture_Variance_Mito_3_00_256,Cyto_Texture_Variance_Mito_3_01_256,Cyto_Texture_Variance_Mito_3_02_256,Cyto_Texture_Variance_Mito_3_03_256,Cyto_Texture_Variance_Mito_5_00_256,Cyto_Texture_Variance_Mito_5_01_256,Cyto_Texture_Variance_Mito_5_02_256,Cyto_Texture_Variance_Mito_5_03_256
0,B1001,A01,EOS100001,10,IMTM,R4,1100,376.0,512.5,511.0,...,22.554693,21.714226,22.126733,21.706818,22.747998,22.737820,22.131124,21.774646,22.613887,22.951774
1,B1001,A02,EOS100089,10,IMTM,R4,387,377.0,513.0,489.0,...,13.415397,13.543335,13.185762,13.186164,13.742171,13.480765,13.012366,13.521472,13.688066,13.431323
2,B1001,A03,EOS100009,10,IMTM,R4,1300,366.0,504.0,488.5,...,25.212769,24.695880,24.789306,24.868424,25.526916,25.174773,24.576415,24.249728,25.125024,24.825614
3,B1001,A04,EOS100097,10,IMTM,R4,1116,381.0,523.5,488.5,...,21.606750,21.524075,21.300508,21.288512,21.769292,21.288239,20.730912,21.357671,21.432836,21.115022
4,B1001,A05,EOS100017,10,IMTM,R4,1242,387.0,529.0,456.5,...,35.863705,36.348848,40.826340,40.014950,41.604687,40.418741,37.847143,38.026442,39.940529,38.071106

# Save raw data

In [12]:
### 
filename = save_path + str(date.today()) + "_IMTM_HepG2_raw.csv"
Data_Bioactives.to_csv(filename, index = False)

## Save missing data

In [13]:
Data_Bioactives_missing = pd.merge(
    Annotation_Bioactives, 
    Data_aggregated, 
    on = ["Metadata_Batch", "Metadata_Plate", "Metadata_Well"], 
    how = "left",
    indicator = True)
        
Data_Bioactives_missing = Data_Bioactives_missing[Data_Bioactives_missing["_merge"] == 'left_only'].dropna(axis='columns')

In [14]:
### 
filename = save_path + str(date.today()) + "_IMTM_HepG2_raw_missing_wells.csv"
Data_Bioactives_missing.to_csv(filename, index = False)

In [15]:
print("There are",len(Data_Bioactives_missing), "missing wells.")

There are 84 missing wells.

In [16]:
Data_Bioactives_missing_counts = Data_Bioactives_missing['Metadata_EOS'].value_counts()
print("There are",len(Data_Bioactives_missing_counts[Data_Bioactives_missing_counts.iloc[:] == 4]), "compounds missing all 4 replicates.")

There are 8 compounds missing all 4 replicates.